# Generated by Django 2.1.3 on 2018-11-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bind', '0002_zone_zones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zones',
            new_name='views',
        ),
    ]
